### ISSUE TITLE
push images?

### ISSUE THREAD

**Issue by ryanking** [GenomicParisCentre/dockerfiles#10]
Do these images get pushed anywhere?

https://hub.docker.com/u/genomicpariscentre/ seems to not have been updated in a while.

**Comment by LehmannN** [comment]
Hello @ryanking , these images are all pushed in the docker hub repository you found. They are regularly updated. You can click on any docker image to see when this was last pushed, e.g. https://hub.docker.com/r/genomicpariscentre/dge-scde/, pushed a few hours ago.

**Comment by ryanking** [comment]
One of the ones I was looking at was samtools (
https://hub.docker.com/r/genomicpariscentre/samtools/) and it says it
hasn’t been pushed for 2 years. Is that right?

**Comment by jourdren** [comment]
Hello @ryanking, our Docker image for samtools 1.4.1 is currently is building. It will be available soon on Docker Hub.

**Comment by jourdren** [comment]
Hello @ryanking, our Docker image for samtools 1.4.1 is currently is building. It will be available soon on Docker Hub.

**Comment by jourdren** [comment]
Hello @ryanking, our Docker image for samtools 1.4.1 is currently is building. It will be available soon on Docker Hub.

**Comment by jourdren** [comment]
Hello @ryanking, our Docker image for samtools 1.4.1 is currently is building. It will be available soon on Docker Hub.
