### ISSUE TITLE
execute using docker

### ISSUE THREAD

**Issue by Chris091089** [GenomicParisCentre/dockerfiles#12]
What is the correct way to run the program once installed from docker, I tried as follows but it does not recognize it
docker run -v / my / data / work / directory: /data genomicpariscentre /porechop porechop -i 18SARS01.fastq.gz -o reads.fastq.gz

**Comment by jourdren** [comment]
When you use our image, you don't need to add the ```poreshop``` command in the command as it is automatically executed with the ENTRYPOINT instruction of our Dockerfile for Porechop:

```bash
docker run -v /my/data/work/directory:/data -w /data genomicpariscentre/porechop:latest -i 18SARS01.fastq.gz -o reads.fastq.gz
```

**Comment by Chris091089** [comment]
I appreciate your attention too much. God bless you
